# importing required packages

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
import pickle as pk

In [2]:
df = pd.read_csv('cardetails.csv')
df

name  year  selling_price  km_driven    fuel  \
0           Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1     Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2         Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3        Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4           Maruti Swift VXI BSIII  2007         130000     120000  Petrol   
...                            ...   ...            ...        ...     ...   
8123             Hyundai i20 Magna  2013         320000     110000  Petrol   
8124         Hyundai Verna CRDi SX  2007         135000     119000  Diesel   
8125        Maruti Swift Dzire ZDi  2009         382000     120000  Diesel   
8126               Tata Indigo CR4  2013         290000      25000  Diesel   
8127               Tata Indigo CR4  2013         290000      25000  Diesel   

     seller_type transmission                 owner     mileage   engine  \
0     Individual       Manual           First Owner   23.4 kmpl  1248 CC   
1     Individual       Manual          Second Owner  21.14 kmpl  1498 CC   
2     Individual       Manual           Third Owner   17.7 kmpl  1497 CC   
3     Individual       Manual           First Owner   23.0 kmpl  1396 CC   
4     Individual       Manual           First Owner   16.1 kmpl  1298 CC   
...          ...          ...                   ...         ...      ...   
8123  Individual       Manual           First Owner   18.5 kmpl  1197 CC   
8124  Individual       Manual  Fourth & Above Owner   16.8 kmpl  1493 CC   
8125  Individual       Manual           First Owner   19.3 kmpl  1248 CC   
8126  Individual       Manual           First Owner  23.57 kmpl  1396 CC   
8127  Individual       Manual           First Owner  23.57 kmpl  1396 CC   

       max_power                     torque  seats  
0         74 bhp             190Nm@ 2000rpm    5.0  
1     103.52 bhp        250Nm@ 1500-2500rpm    5.0  
2         78 bhp      12.7@ 2,700(kgm@ rpm)    5.0  
3         90 bhp   22.4 kgm at 1750-2750rpm    5.0  
4       88.2 bhp      11.5@ 4,500(kgm@ rpm)    5.0  
...          ...                        ...    ...  
8123   82.85 bhp           113.7Nm@ 4000rpm    5.0  
8124     110 bhp  24@ 1,900-2,750(kgm@ rpm)    5.0  
8125    73.9 bhp             190Nm@ 2000rpm    5.0  
8126      70 bhp        140Nm@ 1800-3000rpm    5.0  
8127      70 bhp        140Nm@ 1800-3000rpm    5.0  

[8128 rows x 13 columns]

In [161]:
df.info()#Default is True

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   name           8128 non-null   object 
 1   year           8128 non-null   int64  
 2   selling_price  8128 non-null   int64  
 3   km_driven      8128 non-null   int64  
 4   fuel           8128 non-null   object 
 5   seller_type    8128 non-null   object 
 6   transmission   8128 non-null   object 
 7   owner          8128 non-null   object 
 8   mileage        7907 non-null   object 
 9   engine         7907 non-null   object 
 10  max_power      7913 non-null   object 
 11  torque         7906 non-null   object 
 12  seats          7907 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 825.6+ KB


In [3]:
df.describe()

year  selling_price     km_driven        seats
count  8128.000000   8.128000e+03  8.128000e+03  7907.000000
mean   2013.804011   6.382718e+05  6.981951e+04     5.416719
std       4.044249   8.062534e+05  5.655055e+04     0.959588
min    1983.000000   2.999900e+04  1.000000e+00     2.000000
25%    2011.000000   2.549990e+05  3.500000e+04     5.000000
50%    2015.000000   4.500000e+05  6.000000e+04     5.000000
75%    2017.000000   6.750000e+05  9.800000e+04     5.000000
max    2020.000000   1.000000e+07  2.360457e+06    14.000000

In [4]:
def get_brand_name(car_name):
    car_name=car_name.split(' ')[0]
    return car_name.strip()
    return float(value)

In [5]:
df['name']=df['name'].apply(get_brand_name)

df['mileage'].dtype




dtype('O')

In [6]:
# df['mileage']=df['mileage'].apply(get_brand_name)
# #df['engine']=df['engine'].apply(get_brand_name)
# get_brand_name('23.4 kmpl')

In [7]:
df['mileage'].unique()

array(['23.4 kmpl', '21.14 kmpl', '17.7 kmpl', '23.0 kmpl', '16.1 kmpl',
       '20.14 kmpl', '17.3 km/kg', '23.59 kmpl', '20.0 kmpl',
       '19.01 kmpl', '17.3 kmpl', '19.3 kmpl', nan, '18.9 kmpl',
       '18.15 kmpl', '24.52 kmpl', '19.7 kmpl', '22.54 kmpl', '21.0 kmpl',
       '25.5 kmpl', '26.59 kmpl', '21.5 kmpl', '20.3 kmpl', '21.4 kmpl',
       '24.7 kmpl', '18.2 kmpl', '16.8 kmpl', '24.3 kmpl', '14.0 kmpl',
       '18.6 kmpl', '33.44 km/kg', '23.95 kmpl', '17.0 kmpl',
       '20.63 kmpl', '13.93 kmpl', '16.0 kmpl', '17.8 kmpl', '18.5 kmpl',
       '12.55 kmpl', '12.99 kmpl', '14.8 kmpl', '13.5 kmpl', '26.0 kmpl',
       '20.65 kmpl', '27.3 kmpl', '11.36 kmpl', '17.68 kmpl',
       '14.28 kmpl', '18.53 kmpl', '14.84 kmpl', '21.12 kmpl',
       '20.36 kmpl', '21.27 kmpl', '18.16 kmpl', '22.0 kmpl', '25.1 kmpl',
       '20.51 kmpl', '21.66 kmpl', '25.2 kmpl', '22.9 kmpl', '16.02 kmpl',
       '20.54 kmpl', '22.77 kmpl', '15.71 kmpl', '23.1 kmpl',
       '19.02 kmpl', '19.81 kmpl'

In [8]:
def clear(value):
    # value=value.split('')[0]
    #value=value.strip()
    # if value=='':
    #     value=0
    return float(value)

In [9]:
df["mileage"] = df["mileage"].str.rstrip(" kmpl")
df["mileage"] = df["mileage"].str.rstrip(" km/g")

In [10]:
df["engine"] = df["engine"].str.rstrip(" CC")

In [11]:
df["engine"] = df["engine"].str.rstrip(" CC")

In [12]:
df.shape

(8128, 13)

In [13]:
df.isnull().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

In [14]:
df.dropna(inplace=True)

In [15]:
df.shape

(7906, 13)

In [16]:
df.duplicated().sum()

1208

In [17]:
df.columns

Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner', 'mileage', 'engine', 'max_power', 'torque',
       'seats'],
      dtype='object')

In [18]:
df

name  year  selling_price  km_driven    fuel seller_type  \
0      Maruti  2014         450000     145500  Diesel  Individual   
1       Skoda  2014         370000     120000  Diesel  Individual   
2       Honda  2006         158000     140000  Petrol  Individual   
3     Hyundai  2010         225000     127000  Diesel  Individual   
4      Maruti  2007         130000     120000  Petrol  Individual   
...       ...   ...            ...        ...     ...         ...   
8123  Hyundai  2013         320000     110000  Petrol  Individual   
8124  Hyundai  2007         135000     119000  Diesel  Individual   
8125   Maruti  2009         382000     120000  Diesel  Individual   
8126     Tata  2013         290000      25000  Diesel  Individual   
8127     Tata  2013         290000      25000  Diesel  Individual   

     transmission                 owner mileage engine   max_power  \
0          Manual           First Owner    23.4   1248      74 bhp   
1          Manual          Second Owner   21.14   1498  103.52 bhp   
2          Manual           Third Owner    17.7   1497      78 bhp   
3          Manual           First Owner    23.0   1396      90 bhp   
4          Manual           First Owner    16.1   1298    88.2 bhp   
...           ...                   ...     ...    ...         ...   
8123       Manual           First Owner    18.5   1197   82.85 bhp   
8124       Manual  Fourth & Above Owner    16.8   1493     110 bhp   
8125       Manual           First Owner    19.3   1248    73.9 bhp   
8126       Manual           First Owner   23.57   1396      70 bhp   
8127       Manual           First Owner   23.57   1396      70 bhp   

                         torque  seats  
0                190Nm@ 2000rpm    5.0  
1           250Nm@ 1500-2500rpm    5.0  
2         12.7@ 2,700(kgm@ rpm)    5.0  
3      22.4 kgm at 1750-2750rpm    5.0  
4         11.5@ 4,500(kgm@ rpm)    5.0  
...                         ...    ...  
8123           113.7Nm@ 4000rpm    5.0  
8124  24@ 1,900-2,750(kgm@ rpm)    5.0  
8125             190Nm@ 2000rpm    5.0  
8126        140Nm@ 1800-3000rpm    5.0  
8127        140Nm@ 1800-3000rpm    5.0  

[7906 rows x 13 columns]

In [19]:
df.drop(columns='max_power',inplace=True)#removes all the column value

In [20]:
df

name  year  selling_price  km_driven    fuel seller_type  \
0      Maruti  2014         450000     145500  Diesel  Individual   
1       Skoda  2014         370000     120000  Diesel  Individual   
2       Honda  2006         158000     140000  Petrol  Individual   
3     Hyundai  2010         225000     127000  Diesel  Individual   
4      Maruti  2007         130000     120000  Petrol  Individual   
...       ...   ...            ...        ...     ...         ...   
8123  Hyundai  2013         320000     110000  Petrol  Individual   
8124  Hyundai  2007         135000     119000  Diesel  Individual   
8125   Maruti  2009         382000     120000  Diesel  Individual   
8126     Tata  2013         290000      25000  Diesel  Individual   
8127     Tata  2013         290000      25000  Diesel  Individual   

     transmission                 owner mileage engine  \
0          Manual           First Owner    23.4   1248   
1          Manual          Second Owner   21.14   1498   
2          Manual           Third Owner    17.7   1497   
3          Manual           First Owner    23.0   1396   
4          Manual           First Owner    16.1   1298   
...           ...                   ...     ...    ...   
8123       Manual           First Owner    18.5   1197   
8124       Manual  Fourth & Above Owner    16.8   1493   
8125       Manual           First Owner    19.3   1248   
8126       Manual           First Owner   23.57   1396   
8127       Manual           First Owner   23.57   1396   

                         torque  seats  
0                190Nm@ 2000rpm    5.0  
1           250Nm@ 1500-2500rpm    5.0  
2         12.7@ 2,700(kgm@ rpm)    5.0  
3      22.4 kgm at 1750-2750rpm    5.0  
4         11.5@ 4,500(kgm@ rpm)    5.0  
...                         ...    ...  
8123           113.7Nm@ 4000rpm    5.0  
8124  24@ 1,900-2,750(kgm@ rpm)    5.0  
8125             190Nm@ 2000rpm    5.0  
8126        140Nm@ 1800-3000rpm    5.0  
8127        140Nm@ 1800-3000rpm    5.0  

[7906 rows x 12 columns]

In [21]:
df.info

<bound method DataFrame.info of          name  year  selling_price  km_driven    fuel seller_type  \
0      Maruti  2014         450000     145500  Diesel  Individual   
1       Skoda  2014         370000     120000  Diesel  Individual   
2       Honda  2006         158000     140000  Petrol  Individual   
3     Hyundai  2010         225000     127000  Diesel  Individual   
4      Maruti  2007         130000     120000  Petrol  Individual   
...       ...   ...            ...        ...     ...         ...   
8123  Hyundai  2013         320000     110000  Petrol  Individual   
8124  Hyundai  2007         135000     119000  Diesel  Individual   
8125   Maruti  2009         382000     120000  Diesel  Individual   
8126     Tata  2013         290000      25000  Diesel  Individual   
8127     Tata  2013         290000      25000  Diesel  Individual   

     transmission                 owner mileage engine  \
0          Manual           First Owner    23.4   1248   
1          Manual      

In [22]:
df.drop(columns='torque',inplace=True)#removes all the column value

In [23]:
df

name  year  selling_price  km_driven    fuel seller_type  \
0      Maruti  2014         450000     145500  Diesel  Individual   
1       Skoda  2014         370000     120000  Diesel  Individual   
2       Honda  2006         158000     140000  Petrol  Individual   
3     Hyundai  2010         225000     127000  Diesel  Individual   
4      Maruti  2007         130000     120000  Petrol  Individual   
...       ...   ...            ...        ...     ...         ...   
8123  Hyundai  2013         320000     110000  Petrol  Individual   
8124  Hyundai  2007         135000     119000  Diesel  Individual   
8125   Maruti  2009         382000     120000  Diesel  Individual   
8126     Tata  2013         290000      25000  Diesel  Individual   
8127     Tata  2013         290000      25000  Diesel  Individual   

     transmission                 owner mileage engine  seats  
0          Manual           First Owner    23.4   1248    5.0  
1          Manual          Second Owner   21.14   1498    5.0  
2          Manual           Third Owner    17.7   1497    5.0  
3          Manual           First Owner    23.0   1396    5.0  
4          Manual           First Owner    16.1   1298    5.0  
...           ...                   ...     ...    ...    ...  
8123       Manual           First Owner    18.5   1197    5.0  
8124       Manual  Fourth & Above Owner    16.8   1493    5.0  
8125       Manual           First Owner    19.3   1248    5.0  
8126       Manual           First Owner   23.57   1396    5.0  
8127       Manual           First Owner   23.57   1396    5.0  

[7906 rows x 11 columns]

In [24]:
df['transmission'].unique()

array(['Manual', 'Automatic'], dtype=object)

In [25]:
#replacing objects into binary value classes for prediction

df['transmission'].replace(['Manual','Automatic'],[1,2],inplace=True)

df['transmission']

0       1
1       1
2       1
3       1
4       1
       ..
8123    1
8124    1
8125    1
8126    1
8127    1
Name: transmission, Length: 7906, dtype: int64

In [26]:
df['transmission'].unique()

array([1, 2], dtype=int64)

In [27]:
df['transmission'].replace(['Manual','Automatic'],[1,2],inplace=True)

In [28]:
df['transmission'].unique()

array([1, 2], dtype=int64)

In [29]:
df['seller_type'].unique()

array(['Individual', 'Dealer', 'Trustmark Dealer'], dtype=object)

In [30]:
df['seller_type'].replace(['Individual','Dealer','Trustmark Dealer'],[1,2,3],inplace=True)

In [31]:
df['seller_type'].unique()

array([1, 2, 3], dtype=int64)

In [32]:
df['fuel'].unique()

array(['Diesel', 'Petrol', 'LPG', 'CNG'], dtype=object)

In [33]:
df['fuel'].replace(['Diesel','Petrol','LPG','CNG'],[1,2,3,4],inplace=True)

In [34]:
df['fuel'].unique()

array([1, 2, 3, 4], dtype=int64)

In [35]:
df['name'].unique()

array(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Datsun', 'Jeep', 'Mercedes-Benz',
       'Mitsubishi', 'Audi', 'Volkswagen', 'BMW', 'Nissan', 'Lexus',
       'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo', 'Kia', 'Fiat', 'Force',
       'Ambassador', 'Ashok', 'Isuzu', 'Opel'], dtype=object)

In [36]:
df['name'].replace(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Datsun', 'Jeep', 'Mercedes-Benz',
       'Mitsubishi', 'Audi', 'Volkswagen', 'BMW', 'Nissan', 'Lexus',
       'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo', 'Kia', 'Fiat', 'Force',
       'Ambassador', 'Ashok', 'Isuzu', 'Opel'],[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31],inplace=True)

In [37]:
df['name'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
      dtype=int64)

In [38]:
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth & Above Owner', 'Test Drive Car'], dtype=object)

In [39]:
df['owner'].replace(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth & Above Owner', 'Test Drive Car'],[1,2,3,4,5],inplace=True)

In [40]:
df['owner'].unique()

array([1, 2, 3, 4, 5], dtype=int64)

In [41]:
df

name  year  selling_price  km_driven  fuel  seller_type  transmission  \
0        1  2014         450000     145500     1            1             1   
1        2  2014         370000     120000     1            1             1   
2        3  2006         158000     140000     2            1             1   
3        4  2010         225000     127000     1            1             1   
4        1  2007         130000     120000     2            1             1   
...    ...   ...            ...        ...   ...          ...           ...   
8123     4  2013         320000     110000     2            1             1   
8124     4  2007         135000     119000     1            1             1   
8125     1  2009         382000     120000     1            1             1   
8126     9  2013         290000      25000     1            1             1   
8127     9  2013         290000      25000     1            1             1   

      owner mileage engine  seats  
0         1    23.4   1248    5.0  
1         2   21.14   1498    5.0  
2         3    17.7   1497    5.0  
3         1    23.0   1396    5.0  
4         1    16.1   1298    5.0  
...     ...     ...    ...    ...  
8123      1    18.5   1197    5.0  
8124      4    16.8   1493    5.0  
8125      1    19.3   1248    5.0  
8126      1   23.57   1396    5.0  
8127      1   23.57   1396    5.0  

[7906 rows x 11 columns]

In [42]:
#converting object data type to category data type

df["mileage"] = df["mileage"].astype(float)
df["engine"]=df["engine"].astype(float)

In [43]:
df

name  year  selling_price  km_driven  fuel  seller_type  transmission  \
0        1  2014         450000     145500     1            1             1   
1        2  2014         370000     120000     1            1             1   
2        3  2006         158000     140000     2            1             1   
3        4  2010         225000     127000     1            1             1   
4        1  2007         130000     120000     2            1             1   
...    ...   ...            ...        ...   ...          ...           ...   
8123     4  2013         320000     110000     2            1             1   
8124     4  2007         135000     119000     1            1             1   
8125     1  2009         382000     120000     1            1             1   
8126     9  2013         290000      25000     1            1             1   
8127     9  2013         290000      25000     1            1             1   

      owner  mileage  engine  seats  
0         1    23.40  1248.0    5.0  
1         2    21.14  1498.0    5.0  
2         3    17.70  1497.0    5.0  
3         1    23.00  1396.0    5.0  
4         1    16.10  1298.0    5.0  
...     ...      ...     ...    ...  
8123      1    18.50  1197.0    5.0  
8124      4    16.80  1493.0    5.0  
8125      1    19.30  1248.0    5.0  
8126      1    23.57  1396.0    5.0  
8127      1    23.57  1396.0    5.0  

[7906 rows x 11 columns]

In [235]:
df

name  year  selling_price  km_driven  fuel  seller_type  transmission  \
0        1  2014         450000     145500     1            1             1   
1        2  2014         370000     120000     1            1             1   
2        3  2006         158000     140000     2            1             1   
3        4  2010         225000     127000     1            1             1   
4        1  2007         130000     120000     2            1             1   
...    ...   ...            ...        ...   ...          ...           ...   
8123     4  2013         320000     110000     2            1             1   
8124     4  2007         135000     119000     1            1             1   
8125     1  2009         382000     120000     1            1             1   
8126     9  2013         290000      25000     1            1             1   
8127     9  2013         290000      25000     1            1             1   

      owner  mileage  engine  seats  
0         1    23.40  1248.0    5.0  
1         2    21.14  1498.0    5.0  
2         3    17.70  1497.0    5.0  
3         1    23.00  1396.0    5.0  
4         1    16.10  1298.0    5.0  
...     ...      ...     ...    ...  
8123      1    18.50  1197.0    5.0  
8124      4    16.80  1493.0    5.0  
8125      1    19.30  1248.0    5.0  
8126      1    23.57  1396.0    5.0  
8127      1    23.57  1396.0    5.0  

[7906 rows x 11 columns]

In [44]:
X=df.drop(columns=['selling_price'])
Y=df['selling_price']

In [45]:
X.shape,Y.shape

((7906, 10), (7906,))

In [46]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [47]:
x_train

name  year  km_driven  fuel  seller_type  transmission  owner  mileage  \
3064     1  2006      62900     2            1             1      1    18.90   
2522     7  2013      95000     1            1             1      1    20.46   
1819     7  2017      38000     2            1             1      1    23.01   
6600     8  2015      70000     1            1             1      3    15.40   
7909     9  2018       9500     1            1             1      1    21.50   
...    ...   ...        ...   ...          ...           ...    ...      ...   
5374     1  2019       5000     2            1             1      1    21.40   
5544     3  2016      60000     2            1             1      2    18.50   
888      4  2003      90000     2            1             1      2    13.20   
7820    17  2012     155000     1            1             2      2    16.07   
7479     4  2018      25000     2            1             2      1    17.40   

      engine  seats  
3064   998.0    5.0  
2522  1461.0    5.0  
1819   999.0    5.0  
6600  2179.0    7.0  
7909  1497.0    5.0  
...      ...    ...  
5374  1197.0    5.0  
5544  1198.0    5.0  
888   1495.0    5.0  
7820  1995.0    4.0  
7479  1197.0    5.0  

[6324 rows x 10 columns]

In [48]:
y_train

3064    135000
2522    490000
1819    325000
6600    900000
7909    850000
         ...  
5374    711000
5544    411000
888     110000
7820    900000
7479    800000
Name: selling_price, Length: 6324, dtype: int64

In [49]:
model=LinearRegression()

In [50]:
model.fit(x_train,y_train)

LinearRegression()

In [51]:
model.intercept_

-97908445.9655618

In [52]:
model.coef_

array([ 3.04368277e+04,  4.81918050e+04, -1.66240616e+00, -2.86038903e+04,
        1.02924083e+05,  7.40863366e+05,  6.37600996e+03,  1.24691984e+04,
        6.74627594e+02, -1.31765993e+05])

In [53]:
y_pred = model.predict(x_test)
y_pred

array([ 460376.10068706,  381834.10645308,  378711.85727878, ...,
        418876.34890285, 2412878.3498055 ,  700696.86497673])

In [54]:
model.score(x_test,y_test)

0.5934258070640557

MSE increases exponentially with an increase in error. A good model will have an MSE value closer to zero, indicating a better goodness of fit to the data.

In [55]:
from sklearn.metrics import mean_absolute_percentage_error,mean_squared_error,r2_score


In [105]:
MAE = mean_absolute_percentage_error(y_test,y_pred)
print('MAE',MAE)
MSE = mean_squared_error(y_test,y_pred)
print('MSE',MSE)
r=r2_score(y_test,y_pred)
print('score',r)
p =r.round(2)*100
print('model performence',p,'%')

MAE 0.8746281052285327
MSE 282684141071.9694
score 0.5934258070640557
model performence 59.0 %


Part -2 : Linear regression with standard scalar and minmax scalar 

In [57]:
from sklearn.preprocessing import StandardScaler

In [58]:
scale = StandardScaler()
s = scale.fit_transform(x_train)
s

array([[-0.92086771, -2.05489382, -0.12291363, ..., -0.12321444,
        -0.91752339, -0.43983016],
       [ 0.25296252, -0.25333638,  0.49570532, ...,  0.2597431 ,
        -0.00322097, -0.43983016],
       [ 0.25296252,  0.77612501, -0.60277692, ...,  0.88573137,
        -0.91554865, -0.43983016],
       ...,
       [-0.3339526 , -2.82698987,  0.39934723, ..., -1.52248236,
         0.06392003, -0.43983016],
       [ 2.20934624, -0.51070173,  1.65200241, ..., -0.81793869,
         1.05128766, -1.47886114],
       [-0.3339526 ,  1.03349036, -0.85330796, ..., -0.49144284,
        -0.52455107, -0.43983016]])

In [59]:
s1 = scale.transform(x_test)
s1

array([[-9.20867714e-01,  4.02896418e-03, -2.46283724e-02, ...,
         8.58727959e-01, -4.23839574e-01, -4.39830161e-01],
       [-9.20867714e-01,  2.61394313e-01,  7.84779594e-01, ...,
         1.76456982e+00, -4.23839574e-01, -4.39830161e-01],
       [ 6.44239263e-01, -5.10701733e-01,  2.23015096e+00, ...,
        -4.71639791e-04, -1.13806141e-01, -4.39830161e-01],
       ...,
       [ 5.73241467e-02, -1.02543243e+00, -3.71517501e-01, ...,
         1.46819720e-01, -1.25654552e-01, -4.39830161e-01],
       [ 2.79626136e+00,  7.76125009e-01, -1.16165385e+00, ...,
        -1.42428812e+00,  1.05918660e+00, -4.39830161e-01],
       [-3.33952598e-01,  1.03349036e+00, -8.34036339e-01, ...,
         1.47244196e+00, -5.46273160e-01, -4.39830161e-01]])

In [60]:
model1 = LinearRegression()
model1.fit(s,y_train)

LinearRegression()

In [61]:
model1_y_pred = model1.predict(s1)
model1_y_pred

array([ 460376.10068704,  381834.1064528 ,  378711.85727831, ...,
        418876.34890324, 2412878.34980565,  700696.8649767 ])

In [62]:
model1.coef_

array([ 155576.98302465,  187250.55767045,  -86261.88712814,
        -15490.15077646,   48025.98420944,  250294.65218245,
          4515.5367676 ,   50794.01142777,  341629.38811223,
       -126816.23127532])

In [63]:
model1.intercept_

650379.9544592039

In [106]:
MAE1 = mean_absolute_percentage_error(y_test,model1_y_pred)
print('MAE',MAE1)
MSE1=mean_squared_error(y_test,model1_y_pred)
print('MSE',MSE1)
r1=r2_score(y_test,model1_y_pred)
print('score',r1)
p1 =r1.round(2)*100
print('model performence',p1,'%')

MAE 0.8746281052282603
MSE 282684141072.01776
score 0.5934258070639862
model performence 59.0 %


Creating Model with MinMax Scalar

In [65]:
from sklearn.preprocessing import MinMaxScaler

In [66]:
min= MinMaxScaler()
m = min.fit_transform(x_train)
m

array([[0.        , 0.46153846, 0.04193269, ..., 0.45      , 0.12550336,
        0.375     ],
       [0.2       , 0.73076923, 0.06333271, ..., 0.48714286, 0.28087248,
        0.375     ],
       [0.2       , 0.88461538, 0.02533268, ..., 0.54785714, 0.12583893,
        0.375     ],
       ...,
       [0.1       , 0.34615385, 0.05999937, ..., 0.31428571, 0.29228188,
        0.375     ],
       [0.53333333, 0.69230769, 0.10333274, ..., 0.38261905, 0.46006711,
        0.25      ],
       [0.1       , 0.92307692, 0.01666601, ..., 0.41428571, 0.19228188,
        0.375     ]])

In [67]:
min1 =min.transform(x_test)
min1

array([[0.        , 0.76923077, 0.0453327 , ..., 0.5452381 , 0.20939597,
        0.375     ],
       [0.        , 0.80769231, 0.07333272, ..., 0.63309524, 0.20939597,
        0.375     ],
       [0.26666667, 0.69230769, 0.12333275, ..., 0.46190476, 0.26208054,
        0.375     ],
       ...,
       [0.16666667, 0.61538462, 0.03333269, ..., 0.47619048, 0.26006711,
        0.375     ],
       [0.63333333, 0.88461538, 0.00599934, ..., 0.32380952, 0.4614094 ,
        0.375     ],
       [0.1       , 0.92307692, 0.01733268, ..., 0.6047619 , 0.1885906 ,
        0.375     ]])

In [68]:
model2 = LinearRegression()
model2.fit(m,y_train)


LinearRegression()

In [69]:
model2_y_pred = model1.predict(min1)
model2_y_pred

array([ 866195.91459147,  851432.14928103,  877432.4424128 , ...,
        855272.21440509, 1314869.40546866,  884879.46087887])

In [79]:
model2.coef_


array([  913104.83106488,  1252986.93030512, -2493607.57435155,
         -85811.67090751,   205848.16507534,   740863.36590923,
          25504.03982447,   523706.33080713,  2010390.23053796,
       -1054127.94703404])

In [80]:
model2.intercept_

-804556.4066376466

In [107]:
MAE2 = mean_absolute_percentage_error(y_test,model2_y_pred)
print('MAE',MAE2)
MSE2=mean_squared_error(y_test,model2_y_pred)
print('MSE',MSE2)
r2=r2_score(y_test,model2_y_pred)
print('score',r2)
p2 =r2.round(2)*100
print('model performence',p2,'%')

MAE 1.7812261986188624
MSE 609029091305.9761
score 0.12405587970639798
model performence 12.0 %


Using k - Nearest Neighbours 

In [82]:
from sklearn.neighbors import KNeighborsRegressor

In [83]:
k = KNeighborsRegressor(n_neighbors=5)
k.fit(X,Y)

KNeighborsRegressor()

In [84]:
knn_pred = k.predict(X)
knn_pred

array([402999.8, 538000. , 318600. , ..., 295400. , 371000. , 371000. ])

In [85]:
mse = mean_squared_error(Y,knn_pred)
mse

80855013020.57753

In [115]:
MAE3 = mean_absolute_percentage_error(Y,knn_pred)
print('MAE',MAE3)
MSE3=mean_squared_error(Y,knn_pred)
print('MSE',MSE3)
r3=r2_score(Y,knn_pred)
print('score',r3)
p3 =r3.round(2)*100
print('model performence',p3,'%')

MAE 0.3090745656621295
MSE 80855013020.57753
score 0.8778317296725697
model performence 88.0 %


# Dession Tree Regressor

In [123]:
FinalModel = DecisionTreeRegressor(random_state=0)
FinalModel.fit(x_train,y_train)

y_final_pred = FinalModel.predict(x_test)
y_final_pred


array([ 650000.,  510000.,  168000., ...,  250000., 2678750.,  500000.])

In [121]:
FinalModel.score(x_test,y_test)

0.960894911972977

In [119]:
MAE4 = mean_absolute_percentage_error(y_test,y_test_pred)
print('MAE',MAE4)
MSE4 = mean_squared_error(y_test,y_test_pred)
print('MSE',MSE4)
r4=r2_score(y_test,y_test_pred)
print('score',r3)
p4 =r4.round(2)*100
print('model performence',p4,'%')

MAE 0.18293791127250386
MSE 27189104504.240757
score 0.8778317296725697
model performence 96.0 %


Finalizing the Best model using Mean Square Error

In [101]:
print("Linear Model",MSE)
print("Linear Model with Standard Scalar",MSE1)
print("Linear Model with MinMax Scalar",MSE2)
print("Knearest Neighbour regressor",MSE3)
print("Decision Tree Regressor",MSE4)

Linear Model 282684141071.9694
Linear Model with Standard Scalar 282684141072.01776
Linear Model with MinMax Scalar 609029091305.9761
Knearest Neighbour regressor 80855013020.57753
Decision Tree Regressor 27189104504.240757


In [112]:
print("Linear Model",MAE)
print("Linear Model with Standard Scalar",MAE1)
print("Linear Model with MinMax Scalar",MAE2)
print("Knearest Neighbour regressor",MAE3)
print("Decision Tree Regressor",MAE4)


Linear Model 0.8746281052285327
Linear Model with Standard Scalar 0.8746281052282603
Linear Model with MinMax Scalar 1.7812261986188624
Knearest Neighbour regressor 0.3090745656621295
Decision Tree Regressor 0.18293791127250386


Finalizing the Best model using score

In [117]:
print("Linear Model",r)
print("Linear Model with Standard Scalar",r1)
print("Linear Model with MinMax Scalar",r2)
print("Knearest Neighbour regressor",r3)
print("Decision Tree Regressor",r4)

Linear Model 0.8778317296725697
Linear Model with Standard Scalar 0.5934258070639862
Linear Model with MinMax Scalar 0.12405587970639798
Knearest Neighbour regressor 0.8778317296725697
Decision Tree Regressor 0.960894911972977


In [ ]:
pk.dump(model,open('model.pkl','wb'))